package constants

const (
	REQUIRED_FIELD              = "required_field"
	WRONG_LENGHT                = "wrong_lenght"
	WRONG_FORMAT                = "wrong_format"
	PASSWORD_DOESNT_MATCH       = "password_doesnt_match"
	DATABASE_OPERATION_ERROR    = "database_operation_error"
	EMAIL_ALREADY_EXISTS        = "email_already_exists"
	EMAIL_NOT_FOUND             = "email_not_found"
	EMAIL_ALREADY_VERIFIED      = "email_already_verified"
	USER_NOT_FOUND              = "user_not_found"
	PHONE_NUMBER_NOT_FOUND      = "phone_number_not_found"
	PHONE_NUMBER_ALREADY_EXISTS = "phone_number_already_exists"
	NICKNAME_ALREADY_EXISTS     = "nickname_already_exists"
	INVALID_VERIFICATION_CODE   = "invalid_verification_code"
	INVALID_PASSWORD            = "invalid_password"
	PASSWORDS_NOT_MATCH         = "passwords_not_match"
	EXCEEDED_MAX_VALUE          = "exceeded_max_value"
	EXCEEDED_MIN_VALUE          = "exceeded_min_value"
	PHONE_ALREADY_VERIFIED      = "phone_already_verified"
	MEASUREMENT_NOT_FOUND       = "measurement_not_found"
	MAX_MEASUREMENT_IMAGE_COUNT = "max_measurement_image_count"
	IMAGE_NOT_FOUND             = "image_not_found"
)
